version: "3.9"
services:
  mongo-db:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${KSCRAPER_CORE_ROOT_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${KSCRAPER_CORE_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: kscraper_core_db
    ports:
      - "27017:27017"