spring:
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true

security:
  jwt:
    secret: temp
    validity-in-minutes: 15
    issuer: k-scraper-core
    roles-claim-name: roles

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: INFO