server:
  port: 8099

spring:
  output:
    ansi:
      enabled: ALWAYS
  data:
    mongodb:
      authentication-database: admin
      auto-index-creation: true
      database: kscraper_core_db
      username: ENC(9TokiMSQs9AZgHVXDWv8We/eISVZaJwEopb+2esXd9NoO5VLy7GUqdOjEbjBACcmjiogWnyK09iaXmeuV5qC5Q==)
      password: ENC(IQ05sXzIicOx3nznejl1sFmsmJlb+buAz7xkxL11GQK5Efb/TfByFYSdDaWR44ezlgQHCQ9j2eIZmre4Un1XQA==)

  rabbitmq:
    host: localhost
    port: 5672
    username: ENC(VeK88Zofu2W04mWDrVRCt/DzOBG74hgQo0yi8F3n4MPRfR4qQv2qD/0/q2ql99wAK6luzLzkJE0m2I0V4stxLw==)
    password: ENC(7zl5FcQvwEteA6cqwh5T3Mm0hbD1CzVAotEJDSF8kyeMGV6MNXWENEae7GhcSwFguVjLUap4NYU9r2IRNE+V/w==)

  mail:
    host: smtp.office365.com
    port: 587
    username: ENC(ngJACEKAvvO5OQ0bW6MaxZmvlfxTiQa8Rx5a2U5Kq1gqONqnGSwQRvcWkyfNmTLNEcjljv63GahpkblLubU1Zg==)
    password: ENC(SGU2QchRu/RQ/g5sZ29df6OxNmS54WbBO/ddcM8uBTzh0jgUBhazUcAlPe9cCVhR)
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
      protocol: smtp

springdoc:
  swagger-ui:
    url: /openapi/openapi.yaml

security:
  jwt:
    secret: ENC(ArZ3WAm3OIYNaOSHaDZO2dvfwUMApw6urFi75bUPOxJn+qwYsPNKepPzISrS6Ico+bQkCpbM5aPZojovTfQ7JQ==)
    validity-in-minutes: 15
    issuer: k-scraper-core
    roles-claim-name: roles

scraping:
  max-attempts: 3

rabbitmq:
  exchange:
    scraping: kscraper.core.scraping
  consumer:
    queue:
      scraping-request: "scraping.request"
  producer:
    queue:
      scraping-response: "scraping.response"


jasypt:
  encryptor:
    password: ${JASYPT_PASSWORD}
    algorithm: PBEWITHHMACSHA512ANDAES_256

logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG
    com.shykial.kScraperCore.staticImplementation: DEBUG