spring:
  data:
    mongodb:
      username: kscrapper_core_root
      password: kscrapper_core_pass
      database: kscrapper_core_db
      authentication-database: admin
      auto-index-creation: true
logging:
  level:
    org.springframework.data.mongodb.core.ReactiveMongoTemplate: DEBUG