openapi: 3.0.3
info:
  title: Title
  description: Title
  version: 1.0.0
servers:
  - url: 'http://localhost:8080'
tags:
  - name: Extracting Details
    description: Operations related to extracting details
  - name: Domain Request Details
    description: Operations related to domain request details
paths:
  /extracting-details/{id}:
    get:
      tags:
        - Extracting Details
      operationId: findExtractingDetailsById
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExtractingDetailsResponse'

  /extracting-details:
    get:
      tags:
        - ExtractingDetails
      operationId: findExtractingDetails
      parameters:
        - name: domainId
          in: query
          schema:
            type: string
          required: true
        - name: fieldNames
          in: query
          schema:
            type: array
            items:
              type: string
          required: false
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/ExtractingDetailsResponse'
    post:
      tags:
        - Extracting Details
      operationId: addExtractingDetails
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExtractingDetailsRequest'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddExtractingDetailsResponse'

  /domain-request-details/{id}:
    get:
      tags:
        - Domain Request Details
      operationId: findDomainRequestDetailsById
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainRequestDetailsResponse'

  /domain-request-details:
    get:
      tags:
        - Domain Request Details
      operationId: findDomainRequestDetails
      parameters:
        - name: domainName
          in: query
          description: domain name, should not contain neither http(s) part or www
          example: "google.com"
          schema:
            type: string
          required: true
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainRequestDetailsResponse'
    post:
      tags:
        - Domain Request Details
      operationId: addDomainRequestDetails
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DomainRequestDetailsRequest'
      responses:
        201:
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DomainRequestDetailsResponse'

components:
  schemas:
    ExtractingDetailsRequest:
      type: object
      properties:
        domainId:
          type: string
        extractedFieldsDetails:
          type: array
          items:
            $ref: '#/components/schemas/ExtractedFieldDetails'
      required:
        - domainId
        - extractedFieldsDetails

    AddExtractingDetailsResponse:
      type: object
      properties:
        domainId:
          type: string
        extractedFieldsDetails:
          type: array
          items:
            $ref: '#/components/schemas/ExtractingDetailsResponse'
      required:
        - domainId
        - extractedFieldsDetails

    ExtractingDetailsResponse:
      type: object
      properties:
        id:
          type: string
      allOf:
        - $ref: '#/components/schemas/ExtractedFieldDetails'
      required:
        - id

    ExtractedFieldDetails:
      type: object
      properties:
        fieldName:
          type: string
        selector:
          $ref: '#/components/schemas/Selector'
        extractedPropertyType:
          $ref: '#/components/schemas/ExtractedPropertyType'
        extractedPropertyValue:
          type: string
        base64EncodedRegexReplacements:
          type: object
          additionalProperties:
            type: string
      required:
        - fieldName
        - selector
        - extractedPropertyType

    Selector:
      type: object
      properties:
        value:
          type: string
        index:
          type: integer
      required:
        - value
        - index

    ExtractedPropertyType:
      type: string
      enum:
        - TEXT
        - OWN_TEXT
        - ATTRIBUTE

    DomainRequestDetailsRequest:
      type: object
      properties:
        domainName:
          type: string
        requestHeaders:
          type: object
          additionalProperties:
            type: string
        requestTimeoutInMillis:
          type: integer
      required:
        - domainName

    DomainRequestDetailsResponse:
      type: object
      properties:
        id:
          type: string
      allOf:
        - $ref: '#/components/schemas/DomainRequestDetailsRequest'
      required:
        - id

    ErrorResponse:
      type: object
      properties:
        errorType:
          type: string
          enum:
            - INVALID_INPUT
            - INTERNAL_SEVER_ERROR
            - NOT_FOUND
            - DUPLICATE_DATA
        errorMessage:
          type: string
      required:
        - errorType
        - errorMessage
  parameters:
    Id:
      name: id
      in: path
      schema:
        type: string
      required: true
